#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
MODULES_FILE='/etc/matrix-synapse/conf.d/modules.yaml'

"$SCRIPT_DIR"/get-disposable-email-domains

[ ! -s "$SCRIPT_DIR"/disposable-email-domains.txt ] && printf 'file disposable-email-domains.txt not found.\n' && exit 1

[ -s "$SCRIPT_DIR"/blocked_domains.txt ] && cat "$SCRIPT_DIR"/blocked_domains.txt >> "$SCRIPT_DIR"/disposable-email-domains.txt

if [ -s "$SCRIPT_DIR"/allowed_domains.txt ]; then
	grep -v -x -f "$SCRIPT_DIR"/allowed_domains.txt "$SCRIPT_DIR"/disposable-email-domains.txt > /tmp/blocklist.txt
	sort -u -o /tmp/blocklist.txt{,}
else
	sort -u -o /tmp/blocklist.txt "$SCRIPT_DIR"/disposable-email-domains.txt
fi

sed -i -e '/^$/d' -e '/^#/d' -e 's/^/        - "@/' -e 's/$/"/' /tmp/blocklist.txt

cat "$SCRIPT_DIR"/module_header.txt /tmp/blocklist.txt > "$SCRIPT_DIR"/modules.yaml

if cmp -s "$SCRIPT_DIR"/modules.yaml "$MODULES_FILE"; then
	printf '%s is up-to-date.\n' "$MODULES_FILE"
else
	printf 'backup old modules.yaml and write the new file.\n'
	cp "$MODULES_FILE" "$SCRIPT_DIR"/modules.yaml_bak
	cp "$SCRIPT_DIR"/modules.yaml "$MODULES_FILE"
fi

rm /tmp/blocklist.txt "$SCRIPT_DIR"/disposable-email-domains.txt

exit 0
