#!/usr/bin/env bash

dir='/opt/synapse_blocklist_module'

curl -s -o /tmp/domains.txt https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.txt
curl -s -o /tmp/whitelist.txt https://raw.githubusercontent.com/disposable/disposable/refs/heads/master/whitelist.txt
curl -s -o /tmp/greylist.txt https://raw.githubusercontent.com/disposable/disposable/refs/heads/master/greylist.txt

lists='/tmp/domains.txt /tmp/whitelist.txt /tmp/greylist.txt'
for i in $lists; do
        sed -i -e '/^$/d' -e '/^#/d' "$i"
done

grep -v -x -f /tmp/whitelist.txt /tmp/domains.txt > /tmp/domains.tmp
grep -v -x -f /tmp/greylist.txt /tmp/domains.tmp > "$dir"/disposable-email-domains.txt

rm /tmp/domains.txt /tmp/whitelist.txt /tmp/greylist.txt

exit 0
